name: brick_supabase
description: Supabase connector for Brick, a data persistence library. Includes annotations, adapter, model, and provider.
homepage: https://github.com/GetDutchie/brick/tree/main/packages/brick_supabase
issue_tracker: https://github.com/GetDutchie/brick/issues
repository: https://github.com/GetDutchie/brick

version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  brick_core: ">=1.2.0 <2.0.0"
  collection: ">=1.15.0 <2.0.0"
  logging: ">=1.0.0 <2.0.0"
  meta: ">=1.3.0 <2.0.0"
  supabase: ">=2.3.0 <3.0.0"

dev_dependencies:
  lints: ^2.0.1
  test: ^1.16.5
