name: pizza_shoppe
description: A new Flutter project.

version: 0.1.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  brick_offline_first:
    path: ../packages/brick_offline_first
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  brick_build:
    path: ../packages/brick_build
  build_runner: any
  shelf: any

flutter:
  uses-material-design: true
