name: brick_offline_first_abstract
description: Annotations and models required by the Offline First domain.
homepage: https://github.com/greenbits/brick/tree/master/packages/brick_offline_first_abstract
issue_tracker: https://github.com/greenbits/brick/issues
repository: https://github.com/greenbits/brick

version: 1.0.0-nullsafety.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  meta: ^1.3.0
  brick_core: ^1.0.0-nullsafety.1
  brick_rest: ^1.0.0-nullsafety.0
  brick_sqlite_abstract: ^1.0.0-nullsafety.0
