name: brick_core
description: Interfaces and shared helpers for implementing models, adapters, providers, and repositories in Brick, an intuitive way to work with persistent data in Dart.
homepage: https://github.com/greenbits/brick/tree/master/packages/brick_core
issue_tracker: https://github.com/greenbits/brick/issues
repository: https://github.com/greenbits/brick

version: 1.0.0-nullsafety.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  collection: ^1.15.0

dev_dependencies:
  mockito: ^5.0.0
  test: ^1.16.5
  dart_style: ^1.2.4
