name: brick_offline_first
description: A Brick domain that routes data fetching through local providers
  before remote providers.
homepage: https://github.com/greenbits/brick/tree/master/packages/brick_offline_first
issue_tracker: https://github.com/greenbits/brick/issues
repository: https://github.com/greenbits/brick

version: 1.0.0-nullsafety.0

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.8.0 <2.0.0'

dependencies:
  brick_core: ^1.0.0-nullsafety.1
  brick_offline_first_abstract: ^1.0.0-nullsafety.0
  brick_rest: ^1.0.0-nullsafety.0
  brick_sqlite: ^1.0.0-nullsafety.0
  brick_sqlite_abstract: ^1.0.0-nullsafety.0
  dart_style: ^1.2.4
  http: ^0.13.0
  logging: ^1.0.0
  meta: ^1.3.0
  mockito: ^5.0.0
  path: ^1.8.0
  sqflite: ^2.0.0+1

dev_dependencies:
  test: ^1.16.5
  sqflite_common: ^2.0.0+1
  sqflite_common_ffi: ^2.0.0
  flutter_test:
    sdk: flutter
