name: brick_offline_first
description: A Brick domain that routes data fetching through local providers
  before remote providers.
homepage: https://github.com/GetDutchie/brick/tree/main/packages/brick_offline_first
issue_tracker: https://github.com/GetDutchie/brick/issues
repository: https://github.com/GetDutchie/brick

version: 4.0.1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  brick_core: ">=2.0.0 <3.0.0"
  brick_sqlite: ">=4.0.0 <5.0.0"
  collection: ">=1.15.0 <2.0.0"
  dart_style: ">=3.0.0 <4.0.0"
  http: ">=1.0.0 <2.0.0"
  logging: ">=1.0.0 <2.0.0"
  meta: ">=1.3.0 <2.0.0"
  path: ">=1.9.0 <2.0.0"
  sqflite_common: ">=2.5.0 <3.0.0"

dev_dependencies:
  lints:
  mockito:
  sqflite_common_ffi:
  test:
