name: brick_offline_first_with_graphql_abstract
description: Annotations and models required by the Offline First with GraphQL domain.
homepage: https://github.com/GetDutchie/brick/tree/main/packages/brick_offline_first_abstract_with_graphql
issue_tracker: https://github.com/GetDutchie/brick/issues
repository: https://github.com/GetDutchie/brick

version: 1.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  meta: ">=1.3.0 <2.0.0"
  brick_core: ^1.1.1
  brick_graphql: ">=1.0.3 <3.0.0"
  brick_offline_first_abstract: ">=2.0.0 <3.0.0"
  brick_sqlite_abstract: ">=1.1.0 <2.0.0"

dev_dependencies:
  lints: ^1.0.1
