name: brick_offline_first_with_graphql
description: A Brick domain that routes data fetching through local providers
  before a GraphQL provider.
homepage: https://github.com/GetDutchie/brick/tree/main/packages/brick_offline_first_with_graphql
issue_tracker: https://github.com/GetDutchie/brick/issues
repository: https://github.com/GetDutchie/brick

version: 1.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  brick_core: ^1.1.1
  brick_graphql: ^1.0.1
  brick_offline_first_abstract: ^2.0.0
  brick_offline_first: ">=2.1.0 <3.0.0"
  brick_offline_first_with_graphql_abstract: ^1.0.0
  brick_sqlite: ">=2.0.0 <3.0.0"
  brick_sqlite_abstract: ">=1.1.0 <2.0.0"
  gql: ^0.13.0
  gql_exec: ^0.3.0
  gql_link: ^0.4.0
  logging: ">=1.0.0 <2.0.0"
  meta: ">=1.3.0 <2.0.0"
  sqflite_common: ">=2.0.0 <3.0.0"

dev_dependencies:
  lints: ^1.0.1
  mockito: ^5.0.0
  test: ^1.16.5
  sqflite_common_ffi: ^2.0.0
