name: brick_graphql
description: GraphQL connector for Brick, a data persistence library. Includes annotations, adapter, model, and provider.
homepage: https://github.com/GetDutchie/brick/tree/main/packages/brick_graphql
issue_tracker: https://github.com/GetDutchie/brick/issues
repository: https://github.com/GetDutchie/brick

version: 0.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  brick_core: ^1.1.1
  collection: ^1.15.0
  logging: ^1.0.0
  meta: ^1.3.0
  gql: ^0.13.0
  gql_exec: ^0.3.0
  gql_link: ^0.4.0

dev_dependencies:
  mockito: ^5.0.0
  test: ^1.16.5
  lints: ^1.0.1
