name: brick_build
description: Code generation library and interface for Brick components
homepage: https://github.com/greenbits/brick/tree/master/packages/brick_build
issue_tracker: https://github.com/greenbits/brick/issues
repository: https://github.com/greenbits/brick

version: 0.0.2

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  analyzer: ^0.39.0
  brick_core: ">=0.0.2 <1.0.0"
  brick_sqlite_abstract: ">=0.0.2 <1.0.0"
  brick_offline_first_abstract: ">=0.0.2 <1.0.0"
  build: '>=1.2.0 <2.0.0'
  build_config: '>=0.4.0 <1.0.0'
  dart_style: ">=1.2.4 <2.0.0"
  glob: '>=1.2.0 <2.0.0'
  logging: ^0.11.3+2
  meta: ">=1.1.6 <2.0.0"
  path: ">=1.6.3 <2.0.0"
  source_gen: ^0.9.0

dev_dependencies:
  build_verify: ^1.1.0
  source_gen_test: ^0.1.0+6
  test: ">=1.9.4 <2.0.0"
