name: brick_build
description: Code generation library and interface for Brick components. Useful for creating serdes generators for adapters.
homepage: https://github.com/GetDutchie/brick/tree/main/packages/brick_build
issue_tracker: https://github.com/GetDutchie/brick/issues
repository: https://github.com/GetDutchie/brick

version: 2.0.3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  analyzer: ">=3.2.0 <5.0.0"
  brick_core: ^1.1.1
  build: ^2.2.1
  dart_style: ">=2.0.0 <3.0.0"
  glob: ^2.0.0
  logging: ">=1.0.0 <2.0.0"
  meta: ">=1.3.0 <2.0.0"
  path: ^1.8.0
  source_gen: ^1.0.0

dev_dependencies:
  build_verify: ^2.0.0
  test: ^1.20.1
  lints: ^1.0.1
  brick_build_test:
    path: ../brick_build_test
