name: brick_offline_first_with_supabase_build
description: Code generation library for the Brick Offline First Domain using Supabase
homepage: https://github.com/GetDutchie/brick/tree/main/packages/brick_offline_first_with_supabase_build
issue_tracker: https://github.com/GetDutchie/brick/issues
repository: https://github.com/GetDutchie/brick

version: 2.0.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  analyzer: ">=6.11.0 <8.0.0"
  brick_build: ">=4.0.0 <5.0.0"
  brick_offline_first: ">=4.0.0 <5.0.0"
  brick_offline_first_build: ">=4.0.0 <5.0.0"
  brick_offline_first_with_supabase: ">=2.0.0 <3.0.0"
  brick_sqlite: ">=4.0.0 <5.0.0"
  brick_sqlite_generators: ">=4.0.0 <5.0.0"
  brick_supabase: ">=2.0.0 <3.0.0"
  brick_supabase_generators: ">=2.0.0 <3.0.0"
  build: ">=2.4.2 <2.5.0"
  dart_style: ">=3.0.0 <4.0.0"
  logging: ">=1.0.0 <2.0.0"
  meta: ">=1.3.0 <2.0.0"
  path: ">=1.9.0 <2.0.0"
  source_gen: ">=1.5.0 <3.0.0"

dev_dependencies:
  brick_build_test:
    path: ../brick_build_test
  build_verify:
  lints:
  source_gen_test:
  test:
