name: brick_sqlite
description: SQLite connector for Brick, a data persistence library for Flutter
homepage: https://github.com/GetDutchie/brick/tree/main/packages/brick_sqlite
issue_tracker: https://github.com/GetDutchie/brick/issues
repository: https://github.com/GetDutchie/brick

version: 4.1.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  brick_core: ">=2.0.0 <3.0.0"
  collection: ">=1.15.0 <2.0.0"
  logging: ">=1.0.0 <2.0.0"
  meta: ">=1.3.0 <2.0.0"
  sqflite_common: ">=2.5.0 <3.0.0"
  synchronized: ">=3.1.0 <4.0.0"

dev_dependencies:
  lints:
  mockito:
  sqflite_common_ffi:
  test:
