name: brick_sqlite
description: SQLite connector for Brick, a data persistence library for Flutter
homepage: https://github.com/GetDutchie/brick/tree/main/packages/brick_sqlite
issue_tracker: https://github.com/GetDutchie/brick/issues
repository: https://github.com/GetDutchie/brick

version: 3.0.0-pre.3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  brick_core: ^1.1.1
  collection: ">=1.0.0 <2.0.0"
  logging: ">=1.0.0 <2.0.0"
  meta: ">=1.3.0 <2.0.0"
  sqflite_common: ">=2.0.0 <3.0.0"
  synchronized: ^3.0.0

dev_dependencies:
  test: ^1.16.5
  mockito: ^5.0.0
  sqflite_common_ffi: ^2.0.0
  lints: ^1.0.1
