name: brick_graphql_generators
description: Code generation library for the GraphQL providers, models, and adapters in Brick
homepage: https://github.com/GetDutchie/brick/tree/main/packages/brick_graphql_generators
issue_tracker: https://github.com/GetDutchie/brick/issues
repository: https://github.com/GetDutchie/brick

version: 3.0.0-pre.2

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  analyzer: ">=4.3.1 <6.0.0"
  brick_build: ">=2.1.2 <3.0.0"
  brick_graphql: ">=3.0.0-pre.1 <4.0.0"
  brick_json_generators: ">=1.1.0 <3.0.0"
  build: ">=2.0.0 <3.0.0"
  dart_style: ">=2.0.0 <3.0.0"
  source_gen: ">=1.2.2 <2.0.0"

dev_dependencies:
  test: ^1.20.1
  lints: ^2.0.1
  brick_build_test:
    path: ../brick_build_test
