name: brick_offline_first_example

environment:
  sdk: '>=2.1.0 <3.0.0'
  flutter: '>=1.8.0 <2.0.0'

dependencies:
  flutter:
    sdk: flutter
  brick_core:
    path: ../../brick_core
  brick_offline_first:
    path: ../

dev_dependencies:
  build_runner: any
  build_resolvers: ^1.2.1
  brick_build:
    path: ../../brick_build
