name: brick_sqlite_abstract
description: Annotations and other support for Brick SQLite that does not rely on dart:mirrors
homepage: https://github.com/greenbits/brick/tree/master/packages/brick_sqlite_abstract
issue_tracker: https://github.com/greenbits/brick/issues
repository: https://github.com/greenbits/brick

version: 1.0.0+3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  collection: ^1.15.0
  brick_core: ^1.0.0+1
  meta: ^1.3.0

dev_dependencies:
  lints: any
  test: ^1.16.5
