name: brick_sqlite_abstract
description: Support for Brick SQLite that does not rely on dart:mirrors
homepage: https://github.com/greenbits/brick/tree/master/packages/brick_sqlite_abstract
issue_tracker: https://github.com/greenbits/brick/issues
repository: https://github.com/greenbits/brick

version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  brick_core: ^0.0.6
  meta: ^1.3.0

dev_dependencies:
  test: ^1.16.5
