name: brick_offline_first_with_rest_example

publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dependency_overrides:
  brick_rest:
    path: ../../brick_rest
  brick_offline_first_with_rest:
    path: ../

dev_dependencies:
  build_runner: any
  build_resolvers: any
  brick_offline_first_with_rest_build:
    path: ../../brick_offline_first_with_rest_build
