name: brick_build_test
description: Testing the code generation library and interface for Brick components
homepage: https://github.com/GetDutchie/brick/tree/main/packages/brick_build_test
issue_tracker: https://github.com/GetDutchie/brick/issues
repository: https://github.com/GetDutchie/brick

version: 3.0.0

publish_to: none

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  build: ">=2.4.2 <2.5.0"
  path: ">=1.9.0 <2.0.0"
  source_gen: ">=1.5.0 <3.0.0"
  source_gen_test: ">=1.0.0 <2.0.0"
