name: brick_sqlite_generators
description: Code generation library for the SQLite providers, models, and adapters in Brick
homepage: https://github.com/greenbits/brick/tree/master/packages/brick_sqlite_generators
issue_tracker: https://github.com/greenbits/brick/issues
repository: https://github.com/greenbits/brick

version: 1.0.0+5

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  analyzer: ^1.1.0
  brick_build: ^1.1.0+1
  brick_sqlite_abstract: ^1.0.0+1
  build: ^2.0.0
  dart_style: ^2.0.0
  meta: ^1.3.0
  source_gen: ^1.0.0

dev_dependencies:
  test: ^1.16.8
  lints: any
  brick_build_test:
    path: ../brick_build_test
