name: brick_offline_first_build
description: Code generation library for the Brick Offline First Domain
homepage: https://github.com/GetDutchie/brick/tree/main/packages/brick_offline_first_build
issue_tracker: https://github.com/GetDutchie/brick/issues
repository: https://github.com/GetDutchie/brick

version: 2.1.1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  analyzer: ">=4.3.1 <5.0.0"
  brick_build: ">=2.1.0 <3.0.0"
  brick_core: ^1.1.1
  brick_json_generators: ">=1.1.1 <2.0.0"
  brick_offline_first:
    path: ../brick_offline_first
  brick_sqlite:
    path: ../brick_sqlite
  brick_sqlite_generators:
    path: ../brick_sqlite_generators
  build: ">=2.0.0 <3.0.0"
  dart_style: ">=2.0.0 <3.0.0"
  logging: ">=1.0.0 <2.0.0"
  meta: ">=1.3.0 <2.0.0"
  path: ^1.8.0
  source_gen: ">=1.2.2 <2.0.0"

dev_dependencies:
  brick_build_test:
    path: ../brick_build_test
  brick_offline_first_with_rest:
    path: ../brick_offline_first_with_rest
  brick_rest:
    path: ../brick_rest
  brick_rest_generators:
    path: ../brick_rest_generators
  build_verify: ^2.0.0
  source_gen_test: ^1.0.0
  test: ^1.20.1
  lints: ^1.0.1
