name: brick_json_generators
description: Code generation library for the JSON-like providers, models, and adapters in Brick
homepage: https://github.com/GetDutchie/brick/tree/main/packages/brick_json_generators
issue_tracker: https://github.com/GetDutchie/brick/issues
repository: https://github.com/GetDutchie/brick

version: 1.1.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  analyzer: ">=4.3.1 <5.0.0"
  brick_core: ^1.1.1
  brick_build: ">=2.1.0 <3.0.0"
  build: ">=2.0.0 <3.0.0"
  dart_style: ">=2.0.0 <3.0.0"
  source_gen: ">=1.2.2 <2.0.0"

dependency_overrides:
  brick_build:
    path: ../brick_build

dev_dependencies:
  test: ^1.20.1
  lints: ^1.0.1
  brick_build_test:
    path: ../brick_build_test
