name: brick_offline_first_with_rest_build
description: Code generation library for the Brick Offline First Domain using REST
homepage: https://github.com/greenbits/brick/tree/master/packages/brick_offline_first_with_rest_build
issue_tracker: https://github.com/greenbits/brick/issues
repository: https://github.com/greenbits/brick

version: 1.0.0-nullsafety.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  analyzer: ^1.2.0
  brick_offline_first_abstract: ^1.0.0
  brick_build: ^1.0.0-nullsafety.5
  brick_rest: ^1.0.0
  brick_rest_generators: ^1.0.0-nullsafety.0
  brick_sqlite_abstract: ^1.0.0
  brick_sqlite_generators: ^1.0.0-nullsafety.0
  build: ^2.0.0
  build_config: ^0.4.0
  dart_style: ^2.0.0
  glob: ^2.0.0
  logging: ^1.0.0
  meta: ^1.3.0
  path: ^1.8.0
  source_gen: ^1.0.0

dev_dependencies:
  build_verify: ^2.0.0
  source_gen_test: ^1.0.0
  test: ^1.16.8
