name: brick_offline_first_with_rest_build
description: Code generation library for the Brick Offline First Domain using REST
homepage: https://github.com/greenbits/brick/tree/master/packages/brick_offline_first_with_rest_build
issue_tracker: https://github.com/greenbits/brick/issues
repository: https://github.com/greenbits/brick

version: 0.0.1

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  analyzer: ^0.39.0
  brick_offline_first_abstract: 
    path: ../brick_offline_first_abstract
  brick_rest_generators:
    git:
      url: https://github.com/greenbits/brick.git
      path: packages/brick_rest_generators
  build: ^1.2.0
  build_config: ^0.4.0
  dart_style: ^1.2.4
  glob: ^1.2.0
  logging: ^0.11.3
  meta: ^1.1.6
  path: ^1.6.3
  source_gen: ^0.9.0

dev_dependencies:
  build_verify: ^1.1.0
  source_gen_test: ^0.1.0+6
  test: ">=1.9.4 <2.0.0"

dependency_overrides:
  brick_sqlite_generators:
    path: ../brick_sqlite_generators  
  brick_sqlite_abstract:
    path: ../brick_sqlite_abstract  
