name: pizza_shoppe
description: A new Flutter project.

version: 0.1.0

publish_to: none

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  gql_http_link: any
  sqflite: any

dependency_overrides:
  brick_sqlite_generators:
    path: ../packages/brick_sqlite_generators

dev_dependencies:
  brick_offline_first_with_graphql_build:
    path: ../packages/brick_offline_first_with_graphql_build

  build_runner: any
  shelf: ^1.1.0

flutter:
  uses-material-design: true
