name: pizza_shoppe
description: A new Flutter project.

version: 0.1.0

publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  brick_offline_first_with_graphql:
    path: ../packages/brick_offline_first_with_graphql
  cupertino_icons: ^1.0.2
  gql_http_link: any
  flutter:
    sdk: flutter

dev_dependencies:
  brick_offline_first_with_graphql_build:
    path: ../packages/brick_offline_first_with_graphql_build
  brick_sqlite_generators: ^2.0.0
  build_runner: any
  shelf: ^1.1.0

dependency_overrides:
  brick_build:
    path: ../packages/brick_build

flutter:
  uses-material-design: true
