name: brick_rest
description: RESTful API connector for Brick, a data persistence library. Includes annotations, adapter, model, and provider.
homepage: https://github.com/greenbits/brick/tree/master/packages/brick_rest
issue_tracker: https://github.com/greenbits/brick/issues
repository: https://github.com/greenbits/brick

version: 1.0.0+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  brick_core:
    path: ../brick_core
  http: ^0.13.0
  logging: ^1.0.0
  meta: ^1.3.0

dev_dependencies:
  test: ^1.16.5
