name: brick_offline_first_with_graphql_build
description: Code generation library for the Brick Offline First Domain using GraphQL
homepage: https://github.com/GetDutchie/brick/tree/main/packages/brick_offline_first_with_graphql_build
issue_tracker: https://github.com/GetDutchie/brick/issues
repository: https://github.com/GetDutchie/brick

version: 1.2.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  analyzer: ^1.2.0
  brick_offline_first_abstract:
    path: ../brick_offline_first_abstract
  brick_build: ^1.3.0
  brick_graphql:
    path: ../brick_graphql
  brick_graphql_generators:
    path: ../brick_graphql_generators
  brick_sqlite_abstract: ^1.1.0
  brick_sqlite_generators: ^1.2.0
  build: ^2.0.0
  dart_style: ^2.0.0
  logging: ^1.0.0
  meta: ^1.3.0
  path: ^1.8.0
  source_gen: ^1.0.0
  brick_offline_first_build:
    path: ../brick_offline_first_build

dev_dependencies:
  build_verify: ^2.0.0
  source_gen_test: ^1.0.0
  test: ^1.16.8
  lints: ^1.0.1
  brick_build_test:
    path: ../brick_build_test
