name: brick_offline_first_with_graphql_build
description: Code generation library for the Brick Offline First Domain using GraphQL
homepage: https://github.com/GetDutchie/brick/tree/main/packages/brick_offline_first_with_graphql_build
issue_tracker: https://github.com/GetDutchie/brick/issues
repository: https://github.com/GetDutchie/brick

version: 1.3.1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  analyzer: ">=4.3.1 <5.0.0"
  brick_build: ">=2.1.2 <3.0.0"
  brick_graphql:
    path: ../brick_graphql
  brick_graphql_generators:
    path: ../brick_graphql_generators
  brick_offline_first:
    path: ../brick_offline_first
  brick_offline_first_build:
    path: ../brick_offline_first_build
  brick_offline_first_with_graphql:
    path: ../brick_offline_first_with_graphql
  brick_sqlite:
    path: ../brick_sqlite
  brick_sqlite_generators:
    path: ../brick_sqlite_generators
  build: ">=2.0.0 <3.0.0"
  dart_style: ">=2.0.0 <3.0.0"
  logging: ">=1.0.0 <2.0.0"
  meta: ">=1.3.0 <2.0.0"
  path: ^1.8.0
  source_gen: ">=1.2.2 <2.0.0"

dev_dependencies:
  brick_core: ^1.1.1
  build_verify: ^2.0.0
  lints: ^1.0.1
  source_gen_test: ^1.0.0
  test: ^1.20.1
  brick_build_test:
    path: ../brick_build_test
